version: 2
services:
  # Backend Server
  - type: web
    name: feedback-app-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: feedback-app-db
          property: connectionString

databases:
  - name: feedback-app-db
    databaseName: feedback_app
    user: feedback_user
